name: ML Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pylint
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up DVC
      run: |
        pip install dvc[s3]
        dvc pull
    
    - name: Run linting
      run: |
        pylint src/ || true
    
    - name: Run DVC pipeline
      run: |
        dvc repro
    
    - name: Run tests
      run: |
        python -m pytest tests/ || true

    - name: Push DVC changes
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        dvc push